# Generated by Django 6.0.3 on 2026-03-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('prioridade', models.CharField(choices=[('BA', 'Baixa'), ('ME', 'Média'), ('AL', 'Alta')], default='ME', max_length=2)),
                ('horas_estimadas', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('horas_trabalhadas', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('data', models.DateField()),
            ],
        ),
    ]
