# Generated by Django 6.0.3 on 2026-03-22 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_entradaplanejador'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entradaplanejador',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='entradaplanejador',
            name='hora',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='entradaplanejador',
            unique_together={('tarefa', 'dia_semana', 'periodo', 'hora')},
        ),
    ]
