# Generated by Django 6.0.3 on 2026-03-23 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0003_alter_entradaplanejador_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='horas_estimadas',
            field=models.PositiveIntegerField(default=0, help_text='Minutos estimados'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='horas_trabalhadas',
            field=models.PositiveIntegerField(default=0, help_text='Minutos trabalhados'),
        ),
    ]
