# Generated by Django 6.0.3 on 2026-03-23 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0004_alter_tarefa_horas_estimadas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaTarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dia_tarefas', to='tarefas.tarefa')),
            ],
            options={
                'ordering': ['data', 'tarefa__nome'],
                'unique_together': {('tarefa', 'data')},
            },
        ),
    ]
