# Generated by Django 6.0.3 on 2026-03-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0005_diatarefa'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='hora_cronograda',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
