# Generated by Django 6.0.3 on 2026-03-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0006_tarefa_hora_cronograda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='hora_cronograda',
        ),
        migrations.AddField(
            model_name='diatarefa',
            name='hora_cronograma',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
