# Generated by Django 6.0.3 on 2026-03-29 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0007_remove_tarefa_hora_cronograda_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='diatarefa',
            unique_together={('tarefa', 'data', 'hora_cronograma')},
        ),
    ]
