# Generated by Django 6.0.3 on 2026-03-30 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0008_alter_diatarefa_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarefaFazer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas_a_fazer', to='tarefas.tarefa')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
    ]
