# Generated by Django 6.0.3 on 2026-03-30 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0009_tarefafazer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarefafazer',
            options={'ordering': ['data', 'tarefa__nome']},
        ),
        migrations.AlterField(
            model_name='tarefafazer',
            name='tarefa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas_fazer', to='tarefas.tarefa'),
        ),
        migrations.AlterUniqueTogether(
            name='tarefafazer',
            unique_together={('tarefa', 'data')},
        ),
    ]
