# Generated by Django 6.0.3 on 2026-03-30 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0010_alter_tarefafazer_options_alter_tarefafazer_tarefa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaTarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='tarefa',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas', to='tarefas.categoriatarefa'),
        ),
    ]
