# Generated by Django 6.0.3 on 2026-04-01 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0011_categoriatarefa_tarefa_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarefaHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('prioridade', models.CharField(choices=[('BA', 'Baixa'), ('ME', 'Média'), ('AL', 'Alta')], max_length=2)),
                ('horas_estimadas', models.PositiveIntegerField(default=0, help_text='Minutos estimados')),
                ('horas_trabalhadas', models.PositiveIntegerField(default=0, help_text='Minutos trabalhados')),
                ('data_tarefa', models.DateField()),
                ('categoria_nome', models.CharField(blank=True, max_length=100)),
                ('data_exclusao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Histórico de Tarefa',
                'verbose_name_plural': 'Histórico de Tarefas',
                'ordering': ['-data_exclusao'],
            },
        ),
    ]
