# Generated by Django 6.0.3 on 2026-05-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0012_tarefahistorico'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('ES', 'Em espera'), ('AN', 'Em andamento'), ('CO', 'Concluída')], default='ES', max_length=2),
        ),
    ]
