# Generated by Django 6.0.3 on 2026-05-01 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0013_tarefa_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('horas_trabalhadas', models.PositiveIntegerField(default=0, help_text='Minutos trabalhados')),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtarefas', to='tarefas.tarefa')),
            ],
        ),
    ]
