# Generated by Django 6.0.3 on 2026-05-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0014_subtarefa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtarefa',
            name='horas_trabalhadas',
        ),
        migrations.AddField(
            model_name='subtarefa',
            name='tempo_trabalhado',
            field=models.PositiveIntegerField(default=0, help_text='Tempo trabalhado em minutos'),
        ),
    ]
