from django.urls import path
from . import views

urlpatterns = [
    path('', views.tarefas, name='tarefas'),
    path('especifica/<str:data>/', views.tarefa_especifica,
         name='tarefa_especifica'),
    path('adicionar/', views.adicionar_tarefa, name='adicionar_tarefa'),
    path('adicionar/<str:data>/', views.adicionar_tarefa,
         name='adicionar_tarefa_com_data'),
    path('horas/<int:tarefa_id>/', views.horas_tarefa, name='horas_tarefa'),
    path('deletar/<int:tarefa_id>/', views.deletar_tarefa, name='deletar_tarefa'),
    path('api-guadar-tempo-gasto/', views.api_guardar_tempo_gasto,
         name='api-guadar-tempo-gasto'),
    path('api-tarefas-por-mes/', views.api_tarefas_por_mes,
         name='api-tarefas-por-mes'),
    path('api-dia-tarefa/', views.api_dia_tarefa, name='api-dia-tarefa'),
    path('api-deletar-dia-tarefa/', views.api_deletar_dia_tarefa,
         name='api-deletar-dia-tarefa'),
    path('api-excluir-tarefa-banco/', views.api_excluir_tarefa_banco,
         name='api-excluir-tarefa-banco'),
    path('api-registrar-tempo-trabalhado/', views.api_registrar_tempo_trabalhado,
         name='api-registrar-tempo-trabalhado'),
    path('api-tarefa-fazer/', views.api_tarefa_fazer, name='api-tarefa-fazer'),
    path('api-tarefa-fazer-list/', views.api_tarefa_fazer_list,
         name='api-tarefa-fazer-list'),
    path('api-tarefa-fazer-delete/', views.api_tarefa_fazer_delete,
         name='api-tarefa-fazer-delete'),
    path('api-tarefa-fazer-eventos/', views.api_tarefa_fazer_eventos,
         name='api-tarefa-fazer-eventos'),
    path('api-editar-tarefa/', views.api_editar_tarefa, name='api-editar-tarefa'),
    path('relatorio/categorias/', views.relatorio_categorias,
         name='relatorio_categorias'),
    path('relatorio/tarefas/', views.relatorio_tarefas_categoria,
         name='relatorio_tarefas_categoria'),
]
